################################################################################
# Diagnostic
################################################################################

uint16 id
uint16 cid
uint8 fmi
uint8 wci
uint8 annunc_value
string description
uint16 subsystem
int64 gps_time_sec_us
uint32 service_hour_meter_sec
uint16 occurrence_count
uint8 category
uint8 status
bool last_occurrence_set
uint16 last_occ_duration
uint32 pid
uint32 worst_case_val
uint32 event_trig_val
J1939Name jname
