################################################################################
# LpsSaLoadRecordSubtotal
################################################################################

LoadRecordTimeStamp start_time
LoadRecordTimeStamp end_time
uint32 truck_id
string truck_name
float32 truck_target_weight_tonnes
uint16 target_proportion
uint16 target_passes
uint32 material_id
string material_name
float32 material_density
string custom_list_name1
string custom_list_name2
string custom_list_name3
string custom_list_name4
string tag1
string tag2
string tag3
string tag4
uint8 icon_type
float32 zero_weight
float32 cal_adjust
LoadRecordPass[] passes
float32 weight_tonnes
cpm_common_interfaces/WeighBktWtAccuracy accuracy
