cmake_minimum_required(VERSION 3.8)
project(lps_weigh_app)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(lps_interfaces REQUIRED)
find_package(lps_core REQUIRED)
add_executable(lps_weigh_app_node src/weigh_app_node.cpp)
target_compile_features(lps_weigh_app_node PRIVATE cxx_std_17)
ament_target_dependencies(lps_weigh_app_node rclcpp lps_interfaces lps_core)
install(TARGETS lps_weigh_app_node DESTINATION lib/${PROJECT_NAME})
ament_package()
