#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : sender_3.hpp
// Purpose : Header for Sender3Node.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "rsg_v1_n_1_msg/msg/machine_status.hpp"

namespace rsg_v1_n_1_msg
{

class Sender3Node : public rclcpp::Node
{
public:
  explicit Sender3Node(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~Sender3Node() override;

private:
  void setup_publishers();

  rclcpp::QoS make_qos_reliable_default() const;

  void publish_main_pub();


  // Publishers
  rclcpp::Publisher<rsg_v1_n_1_msg::msg::MachineStatus>::SharedPtr main_pub_;
  rclcpp::TimerBase::SharedPtr main_pub_timer_;
  uint64_t main_pub_count_{0};



};

}  // namespace rsg_v1_n_1_msg
