#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : server.hpp
// Purpose : Header for ServerNode.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "std_srvs/srv/trigger.hpp"

namespace rsg_v1_service_server_std
{

class ServerNode : public rclcpp::Node
{
public:
  explicit ServerNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~ServerNode() override;

private:
  void setup_services();


  void on_request(
    const std::shared_ptr<std_srvs::srv::Trigger::Request> request,
    std::shared_ptr<std_srvs::srv::Trigger::Response> response);




  // Service servers
  rclcpp::Service<std_srvs::srv::Trigger>::SharedPtr main_service_;

};

}  // namespace rsg_v1_service_server_std
