#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : receiver.hpp
// Purpose : Header for ReceiverNode.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "rsg_v1_1_1_msg/msg/machine_status.hpp"

namespace rsg_v1_1_1_msg
{

class ReceiverNode : public rclcpp::Node
{
public:
  explicit ReceiverNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~ReceiverNode() override;

private:
  void setup_subscribers();

  rclcpp::QoS make_qos_reliable_default() const;

  void on_message(const rsg_v1_1_1_msg::msg::MachineStatus::SharedPtr msg);



  // Subscribers
  rclcpp::Subscription<rsg_v1_1_1_msg::msg::MachineStatus>::SharedPtr main_sub_;


};

}  // namespace rsg_v1_1_1_msg
