#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : sender_2.hpp
// Purpose : Header for Sender2Node.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"

namespace rsg_v1_n_n_string
{

class Sender2Node : public rclcpp::Node
{
public:
  explicit Sender2Node(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~Sender2Node() override;

private:
  void setup_publishers();

  rclcpp::QoS make_qos_reliable_default() const;

  void publish_main_pub();


  // Publishers
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr main_pub_;
  rclcpp::TimerBase::SharedPtr main_pub_timer_;
  uint64_t main_pub_count_{0};



};

}  // namespace rsg_v1_n_n_string
