################################################################################
# DemoAppTxChannelStorage
################################################################################

float32 liftposition
float32 liftposition_rate
float32 tiltposition
float32 tiltposition_rate
float32 payload
float32 payload_rate
bool dig
bool wrw
bool llw
bool dump
bool pdump
bool rack
bool carry
float32 weight1
float32 pres_lift_he_demo
float32 pres_lift_re_demo
float32 angle_lift_demo
float32 angle_afe_demo
float32 angle_abc_demo
