################################################################################
# LpsCalIMUResults_t
################################################################################

float32 full_slow_imu_offset_temp1
float32 full_slow_imu_offset_temp2
float32 full_slow_imu_offset_temp3
float32 full_slow_lumped_weight_temp1
float32 full_slow_lumped_weight_temp2
float32 full_slow_lumped_weight_temp3
float32 empty_slow_imu_offset_temp1
float32 empty_slow_imu_offset_temp2
float32 empty_slow_imu_offset_temp3
float32 empty_slow_lumped_weight_temp1
float32 empty_slow_lumped_weight_temp2
float32 empty_slow_lumped_weight_temp3
float32 full_slow_imu_offset_final
float32 empty_slow_imu_offset_final
float32 full_slow_lumped_weight_final
float32 empty_slow_lumped_weight_final
