################################################################################
# LpsSaNvmCalDataChannelStorage::LpsSaNvmCalDataChannel_DataMain_t
################################################################################

float32[11] raise_slow_empty_lift_heights
float32[11] raise_slow_empty_pressures
float32[11] lower_slow_empty_lift_heights
float32[11] lower_slow_empty_pressures
float32[11] raise_slow_full_lift_heights
float32[11] raise_slow_full_pressures
float32[11] lower_slow_full_lift_heights
float32[11] lower_slow_full_pressures
float32 raise_speed_empty_slow
float32 raise_speed_empty_fast
float32 raise_fast_delta_p_empty
float32 raise_speed_full_slow
float32 raise_speed_full_fast
float32 raise_fast_delta_p_full
