################################################################################
# LpsSaNvmCalDataChannelStorage::LpsSaNvmCalDataChannel_DataDebug_t
################################################################################

int32 lift_full_lower_dc_inf_value
int32 lift_full_raise_dc_inf_value
int32 tilt_full_dump_dc_inf_value
int32 tilt_full_rack_dc_inf_value
int32 tilt_dump_stop_angle_inf_value
int32 tilt_rack_stop_angle_inf_value
float32 pcs_vel_slope
float32 pcs_cal_weight
float32 zero_weight
float32 cal_adjust
float32 temp_slope
float32 empty_temp
float32 full_temp
float32 empty_bucket_weight_est
float32 cal_adjust_temp
int32 hyd_oil_type_index
