################################################################################
# LpsSaNvmCalOnTheFlyDataChannelStorage::LpsSaNvmCalOnTheFlyDataChannel_CurveFitInfo_t
################################################################################

bool hyd_oil_temp_met
bool enforce_raise_detent
bool enforce_lower_detent
bool raise_fast_vel_done
bool raise_slow_fit_done
bool raise_fast_fit_done
bool lower_slow_fit_done
uint8 internal_step
uint16 raise_num_points
uint16 lower_num_points
LpsCalIMUResults imu_cal_results
