################################################################################
# LpsSaNvmCalOnTheFlyDataChannelStorage::LpsSaNvmCalOnTheFlyDataChannel_Overrides_t
################################################################################

uint8 lps_cal_ovr_state
int8 lps_cal_app_inf_raise_cmd_lmt
int8 lps_cal_app_inf_lower_cmd_lmt
int8 lps_cal_app_inf_rack_cmd_lmt
int8 lps_cal_app_inf_dump_cmd_lmt
int16 lps_cal_app_inf_eng_spd_lmt
bool lps_cal_app_inf_cal_ovr_active
bool lift_bottom_flag
bool lift_top_flag
bool cal_ovr_acknowledge
float32 lift_valve_cmd_percent
bool lift_in_raise_detent
bool lift_in_lower_detent
bool lift_in_center
bool lift_faulted
bool lever_info_available
LpsSaNvmCalOnTheFlyTiltOverrides tilt_overrides
