################################################################################
# LpsSaNvmCalOnTheFlyDataChannelStorage::LpsSaNvmCalOnTheFlyDataChannel_MiscUpdates_t
################################################################################

int32 lift_he_pres_stat
int32 lift_re_pres_stat
int32 lift_cyl_length_norm_stat
int32 hyd_oil_temp_stat
int32 lift_cyl_vel_stat
int32 tilt_cyl_length_norm_stat
int32 bkt_angle_stat
bool lift_lever_info_lever_info_available
bool lift_lever_info_faulted
