################################################################################
# LpsSaNvmCalOnTheFlyDataChannelStorage::LpsSaNvmCalOnTheFlyDataChannel_DataOnTheFly_t
################################################################################

LpsSaNvmCalOnTheFlyStatusFlags status_flags
LpsSaNvmCalOnTheFlyCurveFitInfo curve_info
LpsSaNvmCalOnTheFlyMiscUpdates cal_updates
LpsSaNvmCalOnTheFlyOverrides cal_overrides
