################################################################################
# LpsSaNvmCalOnTheFlyTiltOverrides_t
################################################################################

uint8 lps_cal_tilt_ovr_state
float32 tilt_noise_max
float32 tilt_noise_min
float32 desired_tilt_extmm
uint8 count_of_samples
float32 tilt_dump_cmd_ovr
bool lps_cal_tilt_ovr_start_request
bool cal_tilt_override_complete
bool cal_tilt_override_fail
