################################################################################
# PartNumbersStorage
################################################################################

string product_id_num
string equipment_id
string sw_group_part_num
string sw_group_release_date
string sw_group_description
string ecm_part_num
string model_num
string ecm_serial_num

bool product_id_num_set
bool sw_group_part_num_set
bool sw_group_release_date_set
bool sw_group_description_set
bool ecm_part_num_set
bool model_num_set
bool ecm_serial_num_set
bool equipment_id_set
