################################################################################
# TipoffAssistOutputs
################################################################################

float32 tilt_sensitivity_out
float32 tilt_pressure_out

float32 arbitrated_payload_norm_error_out
uint8 weigh_status_out

float32 payload_norm_stdev_out
uint8 pcs_weight_accuracy_out

float32 current_weight_norm_error_out
uint8 error_code_out

float32 spill_rate_out

float32 payload_send_to_cpm
uint8 payload_status_send_to_cpm

float32 bucket_payload_target

float32 unsecured_payload_upper_bound_norm
float32 unsecured_payload_lower_bound_norm

uint8 unsecured_pfw_status

float32 min_secure_bucket_angle
