################################################################################
# LpsSaTotalsPrinterCnfg::TruckTicket
################################################################################

uint8 num_copies
bool header_enabled
string header_line1
string header_line2
string header_line3
string footer_line1
bool bucket_weights_enabled
bool truck_weight_enabled
bool truck_id_enabled
bool material_id_enabled
bool store_time_enabled
uint32 ticket_number
uint16 retention_period
