#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : node_b.hpp
// Purpose : Header for NodeB.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"

namespace rsg_v1_three_node_cross_pubsub_matrix
{

class NodeB : public rclcpp::Node
{
public:
  explicit NodeB(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~NodeB() override;

private:
  void setup_publishers();
  void setup_subscribers();

  rclcpp::QoS make_qos_reliable_default() const;

  void publish_b_to_a_report_pub();
  void publish_b_internal_status_pub();
  void on_a_event(const std_msgs::msg::String::SharedPtr msg);
  void on_internal_status(const std_msgs::msg::String::SharedPtr msg);


  // Publishers
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr b_to_a_report_pub_;
  rclcpp::TimerBase::SharedPtr b_to_a_report_pub_timer_;
  uint64_t b_to_a_report_pub_count_{0};
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr b_internal_status_pub_;
  rclcpp::TimerBase::SharedPtr b_internal_status_pub_timer_;
  uint64_t b_internal_status_pub_count_{0};

  // Subscribers
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr a_to_b_event_sub_;
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr b_internal_status_sub_;


};

}  // namespace rsg_v1_three_node_cross_pubsub_matrix
