#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : node_c.hpp
// Purpose : Header for NodeC.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"

namespace rsg_v1_three_node_cross_pubsub_matrix
{

class NodeC : public rclcpp::Node
{
public:
  explicit NodeC(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~NodeC() override;

private:
  void setup_publishers();
  void setup_subscribers();

  rclcpp::QoS make_qos_reliable_default() const;

  void publish_c_to_a_feedback_pub();
  void on_a_status(const std_msgs::msg::String::SharedPtr msg);
  void on_a_command(const std_msgs::msg::String::SharedPtr msg);


  // Publishers
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr c_to_a_feedback_pub_;
  rclcpp::TimerBase::SharedPtr c_to_a_feedback_pub_timer_;
  uint64_t c_to_a_feedback_pub_count_{0};

  // Subscribers
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr a_to_c_status_sub_;
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr a_to_c_command_sub_;


};

}  // namespace rsg_v1_three_node_cross_pubsub_matrix
