#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : node_a.hpp
// Purpose : Header for NodeA.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"

namespace rsg_v1_three_node_cross_pubsub_matrix
{

class NodeA : public rclcpp::Node
{
public:
  explicit NodeA(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~NodeA() override;

private:
  void setup_publishers();
  void setup_subscribers();

  rclcpp::QoS make_qos_reliable_default() const;

  void publish_a_to_c_status_pub();
  void publish_a_to_c_command_pub();
  void publish_a_to_b_event_pub();
  void on_c_feedback(const std_msgs::msg::String::SharedPtr msg);
  void on_b_report(const std_msgs::msg::String::SharedPtr msg);


  // Publishers
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr a_to_c_status_pub_;
  rclcpp::TimerBase::SharedPtr a_to_c_status_pub_timer_;
  uint64_t a_to_c_status_pub_count_{0};
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr a_to_c_command_pub_;
  rclcpp::TimerBase::SharedPtr a_to_c_command_pub_timer_;
  uint64_t a_to_c_command_pub_count_{0};
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr a_to_b_event_pub_;
  rclcpp::TimerBase::SharedPtr a_to_b_event_pub_timer_;
  uint64_t a_to_b_event_pub_count_{0};

  // Subscribers
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr c_to_a_feedback_sub_;
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr b_to_a_report_sub_;


};

}  // namespace rsg_v1_three_node_cross_pubsub_matrix
