################################################################################
# LpsSaUIDisplayState
################################################################################

bool service_mode_enable_code_entered
bool in_service_mode
bool in_verification_mode
uint32 heartbeat_count
uint16 document_id
float32 weight_capacity
int32 weight_decimal_precision
float32 weight_interval
LpsSaUIDisplaySettings settings
