################################################################################
# LpsSaJobMgrReqstCommand
################################################################################

uint8 WRITE_MATERIAL_ID=0
uint8 WRITE_MATERIAL_NAME=1
uint8 WRITE_MATERIAL_DENSITY=2
uint8 WRITE_TRUCK_ID=3
uint8 WRITE_TRUCK_NAME=4
uint8 WRITE_TRUCK_TARGET_WEIGHT=5
uint8 WRITE_TAG1=6
uint8 WRITE_TAG2=7
uint8 WRITE_TAG3=8
uint8 WRITE_TAG4=9
uint8 NONE=10

################################################################################
# LpsSaJobMgrReqst
################################################################################

uint8 command
string arg1
float32 arg2
uint32 arg3
string arg4
