################################################################################
# TiltSensorConfig_t
################################################################################

uint16 TILT_SENSOR_ROTARY_POSITION=451
uint16 TILT_SENSOR_IN_CYLINDER_POSITION=452

################################################################################
# ProdMeasureSensorStatus_t
################################################################################

float32 lift_link_dc
float32 lift_cyl_pos
float32 lift_cyl_he_pres
float32 lift_cyl_re_pres
uint16 tilt_sensor_config
float32 tilt_cyl_he_pres
float32 tilt_cyl_re_pres
float32 tilt_link_dc
float32 hyd_oil_temp
