application:
  name: custom_interfaces_system
  domain_id: 10
  extra_packages:
    - custom_interfaces_pkg
  nodes:
    - sensor_publisher
    - sensor_subscriber
    - sensor_query_server
    - sensor_query_client
