###############################################################################
## @file      SConscript
## @author    autogen
##
## @attention Copyright (C) 2017
## @attention National Robotics Engineering Center
## @attention Carnegie Mellon University
## @attention All rights reserved
## @attention Carnegie Mellon Proprietary
###############################################################################
#!/usr/bin/python
Import( 'baseEnv' )

baseEnv.Append(CPPPATH = ['#apps']);
baseEnv.Append(CPPPATH = ['#apps/include',
			  baseEnv[ 'SSP_DIR'] + '/lps_weighing/include',
			  baseEnv[ 'SSP_DIR'] + '/lps_weighing/src',
			  baseEnv[ 'SSP_DIR'] + '/lps_common/include',
			  baseEnv[ 'SSP_DIR'] + '/lps_app_common/include',
			]);


# Build Channel.Input.so
ifaceChannelInput = baseEnv.SharedLibraryWrapper(
    target='LpsSaWeighDebugChannel.Channel.Input.so',
    source='Channel/Input/channel.cpp',
    LIBS = ['ais_serialization', 'ais_channel', baseEnv['BOOST_SIGNALS'] ],
)

# Build Channel.Output.so
ifaceChannelOutput = baseEnv.SharedLibraryWrapper(
    target='LpsSaWeighDebugChannel.Channel.Output.so',
    source='Channel/Output/channel.cpp',
    LIBS = ['ais_serialization', 'ais_channel' ],
)

# Build Restorable
ifaceRestorable = baseEnv.SharedLibraryWrapper(
    target='LpsSaWeighDebugChannel.Restorable.so',
    source='Restorable/Restorable.cpp',
    LIBS = ['ais_serialization'],
)
    
# Build TypeTraits    
ifaceTypeTraits = baseEnv.SharedLibraryWrapper(
  target='LpsSaWeighDebugChannel.TypeTraits.so',
  source=[
       'TypeTraits/csvable.cpp',
        'TypeTraits/textWritable.cpp',
   ],
   LIBS = ['ais_serialization'],
)

baseEnv.InstallLibrary( ifaceChannelInput )
baseEnv.InstallLibrary( ifaceChannelOutput )
baseEnv.InstallLibrary( ifaceRestorable )
baseEnv.InstallLibrary( ifaceTypeTraits )

baseEnv.Alias("LpsSaWeighDebugChannel", "#lib/libLpsSaWeighDebugChannel.Channel.Input.so")
baseEnv.Alias("LpsSaWeighDebugChannel", "#lib/libLpsSaWeighDebugChannel.Channel.Output.so")
baseEnv.Alias("LpsSaWeighDebugChannel", "#lib/libLpsSaWeighDebugChannel.Restorable.so")
baseEnv.Alias("LpsSaWeighDebugChannel", "#lib/libLpsSaWeighDebugChannel.TypeTraits.so")
