# ==============================================================================
# Parameters grammar
# ------------------------------------------------------------------------------
# No parameters are used in this example.
# ===============================================================================
parameters:
  node_parameters: {}
