#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : client.hpp
// Purpose : Header for ClientNode.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "std_srvs/srv/trigger.hpp"

namespace rsg_v1_service_server_client_std
{

class ClientNode : public rclcpp::Node
{
public:
  explicit ClientNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~ClientNode() override;

private:
  void setup_clients();


  bool wait_for_main_client();
  void call_main_client_async();





  // Service clients
  rclcpp::Client<std_srvs::srv::Trigger>::SharedPtr main_client_;
};

}  // namespace rsg_v1_service_server_client_std
