#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : receiver.hpp
// Purpose : Header for ReceiverNode.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "std_msgs/msg/string.hpp"

namespace rsg_v1_n_1_string
{

class ReceiverNode : public rclcpp::Node
{
public:
  explicit ReceiverNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~ReceiverNode() override;

private:
  void setup_subscribers();

  rclcpp::QoS make_qos_reliable_default() const;

  void on_message(const std_msgs::msg::String::SharedPtr msg);



  // Subscribers
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr main_sub_;


};

}  // namespace rsg_v1_n_1_string
