#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : server.hpp
// Purpose : Header for ServerNode.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "rsg_v1_custom_srv_server_client/srv/set_mode.hpp"

namespace rsg_v1_custom_srv_server_client
{

class ServerNode : public rclcpp::Node
{
public:
  explicit ServerNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~ServerNode() override;

private:
  void setup_services();


  void on_request(
    const std::shared_ptr<rsg_v1_custom_srv_server_client::srv::SetMode::Request> request,
    std::shared_ptr<rsg_v1_custom_srv_server_client::srv::SetMode::Response> response);




  // Service servers
  rclcpp::Service<rsg_v1_custom_srv_server_client::srv::SetMode>::SharedPtr main_service_;

};

}  // namespace rsg_v1_custom_srv_server_client
