#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : receiver.hpp
// Purpose : Header for ReceiverNode.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "rcl_interfaces/msg/set_parameters_result.hpp"
#include "std_msgs/msg/string.hpp"

namespace rsg_v1_service_controlled_sender
{

class ReceiverNode : public rclcpp::Node
{
public:
  explicit ReceiverNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~ReceiverNode() override;

private:
  void declare_parameters();
  void load_parameters();
  void setup_parameter_callbacks();
  rcl_interfaces::msg::SetParametersResult on_parameter_update(
    const std::vector<rclcpp::Parameter> & parameters);
  void setup_subscribers();
  void setup_watchdogs();

  rclcpp::QoS make_qos_reliable_default() const;

  void on_heartbeat(const std_msgs::msg::String::SharedPtr msg);
  void check_watchdog_heartbeat_sub();

  // Parameters
  bool receiving_enabled_;
  OnSetParametersCallbackHandle::SharedPtr parameter_callback_handle_;


  // Subscribers
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr heartbeat_sub_;
  rclcpp::Time heartbeat_sub_last_msg_time_;
  bool heartbeat_sub_has_msg_{false};
  bool heartbeat_sub_idle_{false};
  rclcpp::TimerBase::SharedPtr heartbeat_sub_watchdog_timer_;


};

}  // namespace rsg_v1_service_controlled_sender
