#pragma once

// ============================================================================
// Generated by RSG V1 Core - Option B Inline Layout
// File    : sender.hpp
// Purpose : Header for SenderNode.
// Smart generation:
//   Only declarations for configured features are emitted.
// ============================================================================

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "rclcpp/rclcpp.hpp"
#include "rcl_interfaces/msg/set_parameters_result.hpp"
#include "rsg_v1_service_controlled_sender/srv/set_sending.hpp"
#include "std_msgs/msg/string.hpp"

namespace rsg_v1_service_controlled_sender
{

class SenderNode : public rclcpp::Node
{
public:
  explicit SenderNode(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());
  ~SenderNode() override;

private:
  void declare_parameters();
  void load_parameters();
  void setup_parameter_callbacks();
  rcl_interfaces::msg::SetParametersResult on_parameter_update(
    const std::vector<rclcpp::Parameter> & parameters);
  void setup_publishers();
  void setup_services();

  rclcpp::QoS make_qos_reliable_default() const;

  void publish_heartbeat_pub();
  void on_set_sending_request(
    const std::shared_ptr<rsg_v1_service_controlled_sender::srv::SetSending::Request> request,
    std::shared_ptr<rsg_v1_service_controlled_sender::srv::SetSending::Response> response);

  // Parameters
  double publish_rate_hz_;
  bool enabled_;
  bool sending_enabled_;
  OnSetParametersCallbackHandle::SharedPtr parameter_callback_handle_;

  // Publishers
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr heartbeat_pub_;
  rclcpp::TimerBase::SharedPtr heartbeat_pub_timer_;
  uint64_t heartbeat_pub_count_{0};


  // Service servers
  rclcpp::Service<rsg_v1_service_controlled_sender::srv::SetSending>::SharedPtr set_sending_service_;

};

}  // namespace rsg_v1_service_controlled_sender
